# Generated by Django 5.2.1 on 2025-05-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='situation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
